language: node_js
cache:
  directories:
  - node_modules
node_js:
- 12.19.0
branches:
  only:
  - master
install:
- yarn config set registry https://registry.npm.taobao.org/
- yarn install
scripts:
- yarn run build
addons:
  ssh_known_hosts: 47.98.183.206
  apt:
    packages:
    - sshpass
after_success:
- chmod 600 ~/.ssh/id_rsa
- export SSHPASS=$DEPLOY_PASS
- sshpass -e ssh -o stricthostkeychecking=no root@47.98.183.206 "cd /eric/personal-web/easy-proxy-client
  && git pull origin master && export PATH=/usr/local/node/12.19.0/bin:$PATH && sh
  ./deploy.sh"
env:
  global:
  - secure: cXz3YGHs00jll/Z2k20kc9dIFSKsrmlOLaBAnczZEX87DuGEk/HPZFqcEyX8oD4MKMS3UYvsQAOpOAYynlYnUUuAAcnH0sy9wh5Oi5xD8DPKMmQ87G3uCHUCZ9VjiPw8fOZR3UVf8qG2AnK2gxseX9uGcNz66Z71mFeulYLC9sF5/4rqPpFCXTdGilMcYmXn55eVVevz5jiIkCi8iIzrOixFE1Nki1Q/+TRTRTtuTmyZHVuYARKm9jRz/7zQ1/lShebQUhKFxeslw0excNfaINWxMD7PXx+WxbNznL7eqdINtrfo5eWX4AacWkn1hM8uMizKqQaVtXr7Bd6QFOtnLhutE+vxATWfqakPUIURmYHqOlzbn7Mx5y3D/q81Ec5BjmwA89bufQ4X2hqK0QNwK5p5Ne8Ump4w1NpvhgFnjywDSBgUxbjqulytUIdket9NqgQZo4SffNK+EFu96R6UvVj/nJ7+5sUa01dQzMwKyszWtD2cCKU2gTaMAUktKWVDvLXHsiBIDg/eZBFZAcKPEa+59rYgErz/MDzBNrvrOvrUP2W9RsBolSPKOxzVdr1x8Wd8LXOrZTE5crI4liDkjvq/2sDapv3KeW3k6Wx08slJ//AYKNWphQKHFsYHir+VEumr9dtwJuZzOxMyTh0bs8/ekxDTjbwN8zEs9wDOmCs=
